In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.metrics import (
    accuracy_score, confusion_matrix, classification_report,
    roc_auc_score, roc_curve, mean_squared_error, r2_score
)

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression, LogisticRegression
from sklearn.metrics import confusion_matrix, classification_report

import numpy as np

import seaborn as sns
import numpy as np
import matplotlib as plt
from argon2 import Parameters
from cvxpy.expressions.cvxtypes import parameter
%matplotlib inline
import seaborn as sns

import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline


from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from scipy import stats

import statistics

import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score, precision_score, recall_score


In [2]:
import pandas as pd

df = pd.read_csv('.venv/studs.csv')

In [3]:
df.head

<bound method NDFrame.head of     Study_Hours  Attendance  Pass
0             1          40     0
1             1          45     0
2             1          50     0
3             2          40     0
4             2          45     0
..          ...         ...   ...
87            6          80     1
88            7          85     1
89            8          90     1
90            9          95     1
91           10         100     1

[92 rows x 3 columns]>

In [4]:
df.isnull().sum()

Study_Hours    0
Attendance     0
Pass           0
dtype: int64

In [8]:
X = df.drop('Pass', axis=1)
y = df['Pass']

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [10]:
model = LogisticRegression()
model.fit(X_train, y_train)

LogisticRegression()

In [13]:
y_pred = model.predict(X_test)


print("Accuracy:", accuracy_score(y_test, y_pred))
print("Precision:", precision_score(y_test, y_pred)) #Precision = TP / (TP + FP)

print("Recall:", recall_score(y_test, y_pred))#Recall = TP / (TP + FN), Out of all students who actually passed, how many did the model catch?


Accuracy: 0.9473684210526315
Precision: 0.9090909090909091
Recall: 1.0


In [14]:
confusion_matrix(y_test, y_pred)


array([[ 8,  1],
       [ 0, 10]])

In [13]:
y_test

40    1
22    1
55    0
72    1
0     0
26    1
39    1
67    0
10    0
44    1
83    0
35    1
89    1
62    1
12    0
4     0
18    0
28    1
49    0
Name: Pass, dtype: int64

In [16]:
#CHECK PROBABILITY very imppppppppppp
model.predict_proba(X_test)
#We compare the model’s prediction with the ACTUAL answer (y_test)


array([[1.89540545e-07, 9.99999810e-01],
       [1.17434899e-01, 8.82565101e-01],
       [9.99999900e-01, 9.95095113e-08],
       [2.01546525e-04, 9.99798453e-01],
       [9.99998255e-01, 1.74481636e-06],
       [2.55799532e-02, 9.74420047e-01],
       [7.93678811e-07, 9.99999206e-01],
       [9.98849628e-01, 1.15037166e-03],
       [9.86405246e-01, 1.35947535e-02],
       [3.73942904e-08, 9.99999963e-01],
       [9.97288311e-01, 2.71168850e-03],
       [4.02290964e-06, 9.99995977e-01],
       [4.02290964e-06, 9.99995977e-01],
       [2.12266616e-02, 9.78773338e-01],
       [9.83590912e-01, 1.64090880e-02],
       [9.99962968e-01, 3.70317485e-05],
       [4.02787627e-01, 5.97212373e-01],
       [1.49492005e-03, 9.98505080e-01],
       [9.80205656e-01, 1.97943439e-02]])

In [19]:
y_test

40    1
22    1
55    0
72    1
0     0
26    1
39    1
67    0
10    0
44    1
83    0
35    1
89    1
62    1
12    0
4     0
18    0
28    1
49    0
Name: Pass, dtype: int64

In [20]:
#DECISION BOUNDARY: Decision boundary is the point where the model changes its answer from NO to YES.
model.coef_

array([[1.62308508, 0.2864153 ]])

In [21]:
model.intercept_

array([-26.33855661])

In [32]:
Study_Hours = 5
Attendance = 70


In [33]:
score = (1.62 * Study_Hours) + (0.28 * Attendance) - 26.33
score

1.3700000000000045

In [30]:
if score > 0:
    print('PASS')
else:
    print('FAIL')

FAIL
